### ISSUE TITLE
Administrar música em uma playlist colaborativa

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-eps-mds/2019.1-StreamUs-Frontend#15]
@ygortgaleno commented on [Sat Mar 30 2019](https://github.com/fga-eps-mds/2019.1-StreamUs-Backend/issues/17)

**Eu como** Usuário
**Desejo** administrar as músicas em uma playlist colaborativa
**Para que** seja possível escutar músicas de diversas pessoas presentes na sala

**Descrição:**
Essa issue tem como finalidade administrar as músicas dentro de uma playlist colaborativa

**Critérios de aceitação**
- Adicionar uma música
- Remover uma música
- Reordenar uma música

**Task**
- [x] criar endpoint POST de música
- [x] criar endpoint PUT de música
- [x] criar endpoint DELETE de música

---

@oliveiraMarcelo commented on [Fri May 17 2019](https://github.com/fga-eps-mds/2019.1-StreamUs-Backend/issues/17#issuecomment-493570542)

issue moved to frontend

**Comment by pdaniel37** [comment]
Issue finalizada no commit https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/pull/19/commits/414cebe32345f382355826fff4d61116db4d8deb.
