### ISSUE TITLE
Administrar fila de músicas dentro de uma playlist colaborativa

### ISSUE THREAD

**Issue by iagoomr** [fga-eps-mds/2019.1-StreamUs-Frontend#16]
@ygortgaleno commented on [Sat Mar 30 2019](https://github.com/fga-eps-mds/2019.1-StreamUs-Backend/issues/18)

**Eu como** Usuário
**Desejo** administrar as músicas da fila
**Para que** seja possível editar a fila de reprodução

**Descrição:**
Essa issue tem como objetivo poder administrar as músicas dentro da playlist colaborativa

**Critérios de aceitação**
- Adicionar música na fila de reprodução
- Alterar posição da música na fila de reprodução
- Remover música na fila de reprodução

**Task**
- [x] criar endpoint POST de música na fila de reprodução
- [x] criar endpoint PUT de música na fila de reprodução
- [x] criar endpoint DELETE de música na fila de reprodução

---

@iagoomr commented on [Sat May 18 2019](https://github.com/fga-eps-mds/2019.1-StreamUs-Backend/issues/18#issuecomment-493675985)

Issue moved to Frontend

**Comment by iagoomr** [comment]
A issue foi mesclada com a issue https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/issues/15.
