### ISSUE TITLE
Criar mecanismo de votação para reposicionar uma música na playlist

### ISSUE THREAD

**Issue by LucasPLopes** [fga-eps-mds/2019.1-StreamUs-Frontend#17]
**Eu como** usuário
**Desejo**  votar na música para que ela suba ou desça na sequência da playlist
**Para que**  ela seja priorizada na ordem de execução

**Descrição:**
O usuário irá interagir para alterar a posição da música na playlist:
Se clicado em subir, a posição da música sobe na playlist;
Se clicado em descer, a posição da música desce na playlist.

**Critérios de aceitação**
 - Votar para subir a posição da música na playlist
 - Votar para descer a posição da música na playlist

**Task**
- [ ] criar botão para subir a posição da música
- [ ] criar botão para descer a posição da música
- [ ] as músicas estarem, de fato, sendo reordenadas
