### ISSUE TITLE
Criar componente Administrar Sala

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-eps-mds/2019.1-StreamUs-Frontend#4]
criação do componente Administrar Sala

**Comment by iagoomr** [comment]
@jbisinotti @iagoomr

**Comment by nicaloribeiro** [comment]
**Eu como** usuário
**Desejo** editar uma sala
**Para que** seja possível alterar seus dados

**Descrição :** 
Componente que permita alterar o nome e permissões da sala, assim como excluí-la.

**Critérios de aceitação :**
Os componentes devem ser intuitivos e seguir a paleta de cores juntamente com os StyleSheets padrões.

**Task**

- [x] Criar componente para alterar nome da sala
- [x] Criar componente para alterar permissões da sala
- [x] Criar componente para excluir a sala
- [x] Seguir os stylesheets padrões
